/* North Carolina Soccer Hall of Fame — National Champions Hall of Honor data. */
const champions = [
  {
    year:"2025",name:"'02 CASL Academy Juniors",
    desc:"U-13 Boys National Champions. Earned the title with a 2-1 win over Strikers FC Chingirian (CA-S). Coached by Mark Jonas, Timothy Evans, Sean Nahas, Daniel Popik.",
    img:"https://static.wixstatic.com/media/b61df5_d223129fbbd24b2b8a5627ea1f8024de~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/6%20-%20CASL%20Champs%20(placeholder%20for%20new%20picture).jpg",
    bio:["The '02 CASL Academy Juniors captured the U-13 Boys National Championship, earning their title with a hard-fought 2-1 victory over Strikers FC Chingirian from Southern California.", "Coached by Mark Jonas, Timothy Evans, Sean Nahas, and Daniel Popik, this talented group of young players represented the Capital Area Soccer League and the state of North Carolina with distinction on the national stage.", "Their championship run demonstrated the depth of youth soccer development in North Carolina and the continued tradition of excellence fostered by CASL's academy program."]
  },
  {
    year:"2023",name:"Charlotte Lady Eagles",
    desc:"Under the banner of Missionary Athletes International and Charlotte Eagles Soccer Club. Multiple conference championships across USL W-League and WPSL, with national titles in both leagues and 15+ international mission trips.",
    img:"https://static.wixstatic.com/media/b61df5_74d55ed74eb54a8cb09d9cf9259ac979~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/7%20-%20Hall%20of%20Champions%20Team.jpg",
    bio:["The Charlotte Lady Eagles, operating under the banner of Missionary Athletes International and the Charlotte Eagles Soccer Club, built one of the most unique and successful women's soccer programs in the nation.", "The Lady Eagles achieved multiple conference championships across both the USL W-League and the Women's Premier Soccer League (WPSL), capturing national titles in both leagues. Their on-field success was matched by an extraordinary commitment to service — the program organized more than 15 international mission trips, combining competitive soccer with community outreach around the world.", "Under the leadership of coaches including Lee Horton (NC Soccer HOF, 2007), the Lady Eagles became a model for how competitive athletics and service to others can go hand in hand. Players from across the country were drawn to the program's unique mission and competitive excellence.", "The Charlotte Lady Eagles' legacy extends far beyond trophies and titles. They demonstrated that a soccer program could achieve at the highest levels while maintaining a deep commitment to faith, service, and the development of young women as leaders both on and off the field."]
  },
  {
    year:"2021",name:"1998 & 1999 Raleigh Wings",
    desc:"Women's Soccer Team, USISL W-League. Back-to-back national champions featuring several current and future U.S. Women's National Team players.",
    img:"https://static.wixstatic.com/media/b61df5_38fc7e0a3b7548098efb2a69da7ffa01~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/wings1.jpg",
    bio:["The Raleigh Wings women's soccer team captured back-to-back USISL W-League national championships in 1998 and 1999, establishing themselves as one of the premier women's soccer programs in the country.", "The Wings roster featured an extraordinary collection of talent, including several current and future members of the U.S. Women's National Team. Players such as Siri Mullinix (NC Soccer HOF, 2010), Thori Staples Bryan (NC Soccer HOF, 2021), Megan Jeidy Crotts (NC Soccer HOF, 2024), and Wendy Gebauer Palladino (NC Soccer HOF, 2024) were among those who contributed to the team's dominant run.", "The Wings were also runner-up in 2000, completing a remarkable three-year stretch of excellence. Their success helped raise the profile of women's professional soccer in North Carolina and demonstrated the depth of female soccer talent in the state.", "The Raleigh Wings' championship years coincided with the growing national enthusiasm for women's soccer that culminated in the legendary 1999 FIFA Women's World Cup. The Wings were at the heart of that movement in North Carolina."]
  },
  {
    year:"2020",name:"1993 & 1994 Greensboro Dynamo",
    desc:"USISL National Champions two years running. Founded by English businessman Neil Macpherson, coached by Michael Parker, the Dynamo put Greensboro on the professional soccer map.",
    img:"https://static.wixstatic.com/media/b61df5_e7aff4698d5e4cdf88f042587b80c5ba~mv2.gif",
    bio:["The Greensboro Dynamo captured consecutive USISL national championships in 1993 and 1994, putting the city of Greensboro firmly on the professional soccer map in the United States.", "Founded by English businessman Neil Macpherson and coached by Michael Parker (NC Soccer HOF, 2023), the Dynamo assembled a roster that blended international experience with homegrown North Carolina talent. Eddie Radwanski (NC Soccer HOF, 2020) was named League MVP and National Finals MVP in 1993.", "The Dynamo's back-to-back championships brought professional soccer prominence to the Triad region and helped inspire a generation of young players in the Greensboro area. The excitement generated by the Dynamo's success contributed to the growth of soccer culture in central North Carolina.", "The team's legacy lives on through Macpherson Stadium at Bryan Park, a facility that continues to serve the Greensboro soccer community and host competitive matches to this day."]
  },
  {
    year:"2019",name:"1986 Duke University Men's Soccer",
    desc:"Duke's first national championship in any sport. Under Coach John Rennie, the Blue Devils captured the NCAA Division I title, led by Hermann Award winner John Kerr.",
    img:"https://static.wixstatic.com/media/b61df5_654b78e7bfb4469ab59d0192cd2fcd3f~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Duke-Champions.jpg",
    bio:["The 1986 Duke University men's soccer team achieved something truly historic — they won Duke's first national championship in any sport. Under the leadership of Coach John Rennie (NC Soccer HOF, 2011), the Blue Devils captured the NCAA Division I title, forever cementing their place in both Duke and North Carolina soccer history.", "The team was led by Hermann Award winner John Kerr (NC Soccer HOF, 2019), who captained the squad and provided the skill and leadership that drove the Blue Devils to the pinnacle of college soccer. Kerr would go on to become the first American to play in what is now the English Premier League.", "The 1986 championship validated the growth of soccer in the Atlantic Coast Conference and demonstrated that North Carolina-based programs could compete at the very highest level of collegiate soccer.", "The championship served as a springboard for decades of Duke soccer excellence. The Blue Devils would go on to make multiple additional NCAA tournament appearances and continue producing professional and international players under Rennie's long and distinguished tenure."]
  },
  {
    year:"2019",name:"1996 Greensboro United Navy",
    desc:"Youth national champions representing Greensboro on the national stage.",
    img:"https://static.wixstatic.com/media/b61df5_68c2225067604a9ba81e000b25650d0a~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/GSO-Navy-United.jpg",
    bio:["The 1996 Greensboro United Navy captured a youth national championship, representing the city of Greensboro and the state of North Carolina with distinction on the national stage.", "This talented group of young players emerged from the strong youth soccer development system in the Greensboro area, an ecosystem built over decades by dedicated coaches, administrators, and families.", "Their national championship victory added to Greensboro's growing reputation as a hotbed for youth soccer talent in the Southeast and helped inspire future generations of players in the Triad region."]
  },
  {
    year:"2017",name:"UNC Greensboro Men's Soccer",
    desc:"Multiple NCAA Division III national championships under coaches Michael Berticelli and Michael Parker, later rising through Division II to Division I prominence.",
    img:"https://static.wixstatic.com/media/b61df5_07cbebaff20b453faa5fad97e428456f~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/uncgmen.jpg",
    bio:["The UNC Greensboro men's soccer program stands as one of the most remarkable success stories in North Carolina collegiate soccer history. Under coaches Michael Berticelli (NC Soccer HOF, 2017) and Michael Parker (NC Soccer HOF, 2023), the Spartans captured multiple NCAA national championships and rose through the divisions to become a Division I powerhouse.", "Berticelli led the Spartans to their first Division III national championship in 1982, defeating Bethany (WV) 5-0 in the finals. He followed that with back-to-back titles in 1983, making UNCG the first program to win three consecutive NCAA men's soccer national championships at any level.", "When Parker took over, the tradition of excellence continued. He guided the program through its transition from Division III to Division II and ultimately to Division I, winning additional national titles along the way. Parker's teams won the Division III championship in 1985, 1986, and 1987, and were Division II national runners-up in 1989.", "At the Division I level, the Spartans became a consistent force in the Southern Conference and a regular NCAA tournament participant. Parker's teams spent multiple weeks ranked No. 1 in the nation and advanced to the Round of 16 in four consecutive years (2004-2006, 2008).", "The UNCG program produced numerous All-Americans, professional players, and coaches who went on to make their own marks on the game. The Spartans' journey from Division III startup to Division I contender is a testament to the vision, dedication, and excellence of everyone involved with the program."]
  },
  {
    year:"2015",name:"1988 CASL Elite",
    desc:"Capital Area Soccer League's elite youth team, representing North Carolina excellence in youth development and competition at the national level.",
    img:"https://static.wixstatic.com/media/b61df5_6753f2c5bd7b4af7a2a9cff7620746d1~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Elite-group-web%20(1).jpg",
    bio:["The 1988 CASL Elite team represented the best of the Capital Area Soccer League's youth development program, achieving national-level success that brought recognition to North Carolina's growing excellence in youth soccer.", "The team's accomplishments on the national stage demonstrated the quality of coaching and player development within CASL, one of the most respected soccer organizations in the southeastern United States.", "Their success helped establish CASL as a pipeline for elite talent, contributing to the broader growth of competitive youth soccer in North Carolina and inspiring future generations of players in the Raleigh area."]
  },
  {
    year:"2014",name:"University of North Carolina Women's Soccer",
    desc:"The most dominant program in collegiate women's soccer history. Under Anson Dorrance, the Tar Heels have won 22 NCAA national championships.",
    img:"https://static.wixstatic.com/media/b61df5_c95ac7e230dd45629237ff53c9f34f41~mv2.gif",
    bio:["The University of North Carolina women's soccer program is, quite simply, the most dominant program in the history of collegiate women's soccer — and arguably in the history of any collegiate sport. Under the legendary coaching of Anson Dorrance (NC Soccer HOF, 2002), the Tar Heels have won 22 NCAA national championships.", "Dorrance became the head coach when Carolina made women's soccer a varsity sport in 1979. The dynasty began immediately — the Tar Heels won the AIAW title in 1981 and then captured the first three NCAA championships when the NCAA began conducting women's soccer tournaments in 1982.", "The numbers are staggering. Through decades of dominance, the Tar Heels have amassed a winning percentage above .940, won the ACC Championship 15 times, and produced a seemingly endless stream of All-Americans, professional players, and U.S. Women's National Team members.", "The program's alumni reads like a who's who of women's soccer: Mia Hamm (NC Soccer HOF, 2008), Carla Overbeck (NC Soccer HOF, 2001), Cindy Parlow Cone (NC Soccer HOF, 2017), and countless others went on to represent the United States in World Cups and Olympics.", "The UNC women's soccer program has been a driving force behind the growth of women's soccer in the United States. Their sustained excellence set the standard that every other program aspires to reach, and their impact on the sport extends far beyond Chapel Hill. As legendary UNC basketball coach Dean Smith once said, Carolina is \"a women's soccer school.\""]
  },
  {
    year:"2013",name:"1977 CASL Spartans",
    desc:"North Carolina's first youth national championship in soccer. US Youth Soccer National Champions, blazing a trail for future generations of NC youth players.",
    img:"https://static.wixstatic.com/media/b61df5_b4846c6e409441adb34167253b8dd4ac~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Spartans-for-HOF-Web-1.jpg",
    bio:["The 1977 CASL Spartans hold a special place in North Carolina soccer history as the winners of the state's first youth national championship in soccer. Coached by Israel \"Izzy\" Hernandez (NC Soccer HOF, 2009), the Spartans captured the US Youth Soccer National Championship in 1995.", "The team's journey to the national title was a breakthrough moment for North Carolina youth soccer. Their success demonstrated that players developed in the Tar Heel state could compete with and defeat the best youth talent from across the country.", "The Spartans' championship blazed a trail for future generations of North Carolina youth players and validated the work of the coaches, administrators, and families who had invested in building competitive youth soccer programs in the state.", "Many members of the Spartans went on to successful playing careers at the collegiate level and beyond, carrying forward the competitive spirit and love of the game that defined their championship season."]
  },
  {
    year:"2012",name:"1981 Carolina Lightnin'",
    desc:"American Soccer League Champions in their inaugural season. Led by coach Rodney Marsh, the Lightnin' won the title before 20,163 fans in Charlotte's Memorial Stadium.",
    img:"https://static.wixstatic.com/media/b61df5_e602d2cd6ba1409d955f0c03d754fc02~mv2.jpg/v1/fill/w_800,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/1981-Carolina-Lightnin-RAW_edited.jpg",
    bio:["The 1981 Carolina Lightnin' wrote one of the most remarkable chapters in North Carolina sports history by winning the American Soccer League Championship in their very first season of existence.", "Founded by visionary owner Bob Benson (NC Soccer HOF, 2023) and coached by English football legend Rodney Marsh (NC Soccer HOF, 2024), the Lightnin' captured the hearts of Charlotte and the entire Carolinas region. The championship match — a thrilling 2-1 overtime victory over NY United — was played before 20,163 fans at Charlotte's American Memorial Legion Stadium.", "Marsh assembled a roster that blended international talent with local players, including Tony Suarez (NC Soccer HOF, 2012) and Bill Finneyfrock (NC Soccer HOF, 2012). The team also featured future US Soccer Hall of Famer Paul Child and, remarkably, had Bobby Moore — captain of England's 1966 World Cup team — as an assistant coach.", "The Lightnin' led the ASL in average attendance every year they played, proving that professional soccer could thrive in the Carolinas. Their success is widely credited with helping pave the way for future professional sports franchises in Charlotte, including the NBA Hornets, NFL Panthers, and Charlotte FC.", "The Carolina Lightnin' were the first team inducted into the NCSHOF's National Champions Hall of Honor in 2012, a fitting tribute to a team that ignited the passion for professional soccer in North Carolina."]
  }
];
